### ISSUE TITLE
Sync exports used

### ISSUE THREAD

**Issue by Halama** [keboola/luckyguess-bundle#6]
Vypadá to že to pořád používá sync exporty:
![image](https://user-images.githubusercontent.com/903531/31329360-04e62930-acda-11e7-9a22-c4f62913ccc0.png)

https://connection.keboola.com/admin/projects/236/application/?app=kbc.docToolRecipesApp#/rcp-basket/323153166

**Comment by Halama** [comment]
![image](https://user-images.githubusercontent.com/903531/31329377-1c66a5e4-acda-11e7-9285-73edc165efc4.png)

**Comment by Halama** [comment]
to je divný v kodu to vypadá že to používá async, možná to není nasazený, jdu to zkontrolovat.

**Comment by Halama** [comment]
https://github.com/keboola/luckyguess-bundle/blob/915f8fb598297f159fadb803f3a96868d7071841/TableReader.php#L65

**Comment by Halama** [comment]
je tam nasazený starý tag https://github.com/keboola/luckyguess-bundle/blob/d_20170912_1817/TableReader.php#L63

**Comment by Halama** [comment]
ale v posledním deploy vše vypadalo ok a production branch taky byla aktuální https://jenkins.keboola.com/job/Deploy%20-%20rt-lucky-guess/191/console

**Comment by Halama** [comment]
spustil jsem deploy znovu a pořád tam vidím starý tag wtf. https://jenkins.keboola.com/job/Deploy%20-%20rt-lucky-guess/192/console

**Comment by Halama** [comment]
Nasel jsem to, v nastavení deploye chyběl deploy na API servery. Pouštím znovu.

**Comment by Halama** [comment]
Funguje to:
![image](https://user-images.githubusercontent.com/903531/31329973-bd7191e0-acdc-11e7-80a1-216803f253f8.png)

**Comment by odinuv** [comment]
🤦‍♂️
